In [1]:
using CSV

In [1]:
datafile = "/home/ctroupin/data/EMODnet/Statistics/stats20220101_20220331_short.csv"

"/home/ctroupin/data/EMODnet/Statistics/stats20220101_20220331_short.csv"

In [2]:
column_names = ["Label", "Visits", "Events", "Events with a value",
    "Event value", "Minimum Event value", "Maximum Event value",
    "Unique visitors (daily sum)",
    "The average of all values for this event",
    "Metadata: Events_EventName",
    "Metadata: Events_EventAction", "Metadata: is_summary"
]

12-element Vector{String}:
 "Label"
 "Visits"
 "Events"
 "Events with a value"
 "Event value"
 "Minimum Event value"
 "Maximum Event value"
 "Unique visitors (daily sum)"
 "The average of all values for this event"
 "Metadata: Events_EventName"
 "Metadata: Events_EventAction"
 "Metadata: is_summary"

In [3]:
df = open(datafile, "r")
line1 = readline(df);
ii = 1
labels = Vector{String}
for lines in readlines(df)
    println(lines)
    println("")
    linesplit = split(lines, ",")
    println(linesplit[1])
    ii += 1
end
@info("number of lines: $(ii)")
close(df)

null - UUID,104,304,0,0,0,0,104,0,null,UUID,

null - UUID
chlorophyll - Layer,48,60,0,0,0,0,48,0,chlorophyll,Layer,

chlorophyll - Layer
Others,45,56,0,0,0,0,45,0,Others,,1

Others
a8e66da6-ebac-4c4d-96cb-4542eb66894b - UUID,42,84,0,0,0,0,42,0,a8e66da6-ebac-4c4d-96cb-4542eb66894b,UUID,

a8e66da6-ebac-4c4d-96cb-4542eb66894b - UUID
bl_totalabundance_monitoring - Layer,42,74,0,0,0,0,42,0,bl_totalabundance_monitoring,Layer,

bl_totalabundance_monitoring - Layer
shown - form,39,85,0,0,0,0,39,0,shown,fo

[ Info: number of lines: 20


In [4]:
Vector{String}(undef, 520)

520-element Vector{String}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
   ⋮
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [10]:
?split

search: split splitext splitdir splitpath splitdrive rsplit eachsplit splice!



```
split(str::AbstractString, dlm; limit::Integer=0, keepempty::Bool=true)
split(str::AbstractString; limit::Integer=0, keepempty::Bool=false)
```

Split `str` into an array of substrings on occurrences of the delimiter(s) `dlm`.  `dlm` can be any of the formats allowed by [`findnext`](@ref)'s first argument (i.e. as a string, regular expression or a function), or as a single character or collection of characters.

If `dlm` is omitted, it defaults to [`isspace`](@ref).

The optional keyword arguments are:

  * `limit`: the maximum size of the result. `limit=0` implies no maximum (default)
  * `keepempty`: whether empty fields should be kept in the result. Default is `false` without a `dlm` argument, `true` with a `dlm` argument.

See also [`rsplit`](@ref), [`eachsplit`](@ref).

# Examples

```jldoctest
julia> a = "Ma.rch"
"Ma.rch"

julia> split(a, ".")
2-element Vector{SubString{String}}:
 "Ma"
 "rch"
```
